apiVersion: v1
kind: Service
metadata:
  name: kube-drug-annotations-svc
spec:
  type: ClusterIP
  selector:
    app: drug-annotations
  ports:
    - port: 80
      targetPort: http
      name: http
      protocol: TCP
    - port: 5000
      name: api
      targetPort: api
      protocol: TCP
